### ISSUE TITLE
Bug: Class "Illuminate\Log\LogManager" not found

### ISSUE THREAD

**Issue by Twansparant** [roots/acorn#217]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
I changed some code in my sage 10 theme and all of a sudden I get this fatal error:
```
Fatal error: Declaration of Illuminate\Log\LogManager::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void in /srv/www/mydomain.test/current/vendor/illuminate/log/LogManager.php on line 546
```

#### What have you tried?
• I tried downgrading Acorn to 2.0.4
• Run `composer update`
• Check if that `LogManager` class is actually there (and it is)

#### What insights have you gained?
I bumped into this topic: https://laracasts.com/discuss/channels/servers/class-logmanager-not-found-in-logserviceprovider-after-upgrade-to-php81
and read it's related to PHP 8.1 which I'm also running, but that it should be resolved with Laravel 8.76+, I've got versions  v8.83.6 installed.

#### Possible solutions
Try to install PHP 8.0 version with `phpenv`.

### Steps To Reproduce

1. Use php version 8.1
1. Install latest version of Acorn 2.0.5
1. Re-produce an error in your code somewhere

### Expected Behavior

I expect the error to be logged with the `LogManager`.

### Actual Behavior

No error is logged, but instead I get the fatal error.

### Relevant Log Output

```shell
Fatal error: Declaration of Illuminate\Log\LogManager::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void in /srv/www/mydomain.test/current/vendor/illuminate/log/LogManager.php on line 546

Fatal error: Uncaught Error: Class "Illuminate\Log\LogManager" not found in /srv/www/mydomain.test/current/vendor/illuminate/log/LogServiceProvider.php:17 Stack trace: #0 /srv/www/mydomain.test/current/vendor/illuminate/container/Container.php(873): Illuminate\Log\LogServiceProvider->Illuminate\Log\{closure}(Object(Roots\Acorn\Application), Array) #1 /srv/www/mydomain.test/current/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build(Object(Closure)) #2 /srv/www/mydomain.test/current/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(851): Illuminate\Container\Container->resolve('log', Array, true) #3 /srv/www/mydomain.test/current/vendor/illuminate/container/Container.php(694): Illuminate\Foundation\Application->resolve('log', Array) #4 /srv/www/mydomain.test/current/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(836): Illuminate\Container\Container->make('log', Array) #5 /srv/www/mydomain.test/current/vendor/roots/acorn/src/Illuminate/Foundation/Exceptions/Handler.php(242): Illuminate\Foundation\Application->make('log') #6 /srv/www/mydomain.test/current/vendor/roots/acorn/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(162): Illuminate\Foundation\Exceptions\Handler->report(Object(Symfony\Component\ErrorHandler\Error\FatalError)) #7 /srv/www/mydomain.test/current/vendor/roots/acorn/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(204): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError)) #8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown() #9 {main} thrown in /srv/www/mydomain.test/current/vendor/illuminate/log/LogServiceProvider.php on line 17
```

### Versions
PHP 8.1.4
Composer 2.2.10
Sage 10.1.2
Acorn 2.0.5

**Comment by Twansparant** [comment]
If I add php version **7.4** to the platform config in my theme's **composer.json**:

```json
  "config": {
    "optimize-autoloader": true,
    "preferred-install": "dist",
    "sort-packages": true,
    "platform": {
      "php": "7.4"
    }
  },
```
And after run:

```shell
rm -rf vendor && rm composer.lock && composer install
```
The error is gone and running `wp @development acorn optimize` runs without error:

```shell
Configuration cache cleared!
Configuration cached successfully!
Files cached successfully!
```

If I remove the php version from my config, the same command results in the error as described:

```shell
Configuration cache cleared!
Configuration cached successfully!
Fatal error: Declaration of Illuminate\Log\LogManager::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void in /srv/www/cms.clarify.nl/current/vendor/illuminate/log/LogManager.php on line 546
Fatal error: Uncaught Error: Class "Illuminate\Log\LogManager" not found in /srv/www/cms.clarify.nl/current/vendor/illuminate/log/LogServiceProvider.php:17
Stack trace:
#0 /srv/www/cms.clarify.nl/current/vendor/illuminate/container/Container.php(873): Illuminate\Log\LogServiceProvider->Illuminate\Log\{closure}(Object(Roots\Acorn\Application), Array)
#1 /srv/www/cms.clarify.nl/current/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build(Object(Closure))
#2 /srv/www/cms.clarify.nl/current/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(851): Illuminate\Container\Container->resolve('log', Array, true)
#3 /srv/www/cms.clarify.nl/current/vendor/illuminate/container/Container.php(694): Illuminate\Foundation\Application->resolve('log', Array)
#4 /srv/www/cms.clarify.nl/current/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(836): Illuminate\Container\Container->make('log', Array)
#5 /srv/www/cms.clarify.nl/current/vendor/roots/acorn/src/Illuminate/Foundation/Exceptions/Handler.php(242): Illuminate\Foundation\Application->make('log')
#6 /srv/www/cms.clarify.nl/current/vendor/roots/acorn/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(162): Illuminate\Foundation\Exceptions\Handler->report(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#7 /srv/www/cms.clarify.nl/current/vendor/roots/acorn/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(204): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#9 {main}
  thrown in /srv/www/cms.clarify.nl/current/vendor/illuminate/log/LogServiceProvider.php on line 17
Error: Cannot connect over SSH using provided configuration.
```

**Comment by QWp6t** [comment]
This seems like it's an upstream issue that's out of my control.

The good news is that I think it's been fixed in PHP v8.1.6

- https://github.com/php/php-src/pull/8297
- https://github.com/php/php-src/issues/8164#issuecomment-1105036240

**Comment by Twansparant** [comment]
I still don't understand this bug to be honest...
My Trellis servers run php 8.0, my local machine currently runs php 8.1.9 (I upgraded from 8.1.4) and I'm still getting this bug?

In my `composer.json` I define the php platform like this:
```
  ...
  "require": {
    "php": ">=7.1",
    "composer/installers": "^2.1",
    "vlucas/phpdotenv": "^5.4",
    "oscarotero/env": "^2.1",
    "roots/acorn": "^2.1",
    "roots/bedrock-autoloader": "^1.0",
    "roots/bedrock-disallow-indexing": "^2.0",
    "roots/wordpress": "^6.0",
    "roots/wp-config": "^1.0",
    "roots/wp-password-bcrypt": "^1.1",
    ...
  },
  "require-dev": {
    "squizlabs/php_codesniffer": "^3.6.0",
    "roave/security-advisories": "dev-latest"
  },
  "config": {
    "optimize-autoloader": true,
    "preferred-install": "dist",
    "allow-plugins": {
      "ffraenz/private-composer-installer": true,
      "junaidbhura/composer-wp-pro-plugins": true,
      "composer/installers": true,
      "roots/wordpress-core-installer": true
    },
    "platform": {
      "php": "8.0"
    }
  },
  ...
  "scripts": {
    "post-root-package-install": [
      "php -r \"copy('.env.example', '.env');\""
    ],
    "post-autoload-dump": [
      "Roots\\Acorn\\ComposerScripts::postAutoloadDump"
    ],
    "test": [
      "phpcs"
    ]
  }
 ```
So what is triggering this bug?
Can I only get rid of this bug by using php **8.1** on my servers too?
Or should I use the special [acorn-v2.1.2-php-8.0.zip](https://github.com/roots/acorn/releases/download/v2.1.2/acorn-v2.1.2-php-8.0.zip)?

Because I did try that by defining the repository like this:
```
    {
      "type": "package",
      "package": {
        "name": "roots/acorn",
        "version": "2.1.2",
        "type": "library",
        "dist": {
          "url": "https://github.com/roots/acorn/releases/download/v2.1.2/acorn-v2.1.2-php-8.0.zip",
          "type": "zip"
        }
      }
    },
```
But then I get the `You need to install Acorn to use this theme.` message because it can't use the `post-autoload-dump` script:
```
Class Roots\Acorn\ComposerScripts is not autoloadable, can not call post-autoload-dump script
```

Any insight would be very helpful, thanks!

**Comment by Twansparant** [comment]
So in the end I tried installing the `3.0.0-alpha.3` Acorn version and tweaked my Sage's `functions.php` accordingly and that DID work...
